concept_prompts = {"round_bird": ["Watercolor painting of {} on a branch",
                                  "A house in style of {}",
                                  "Grainy photo of {} in angry birds",
                                  "{} made of chocolate",
                                  "Ukiyo-e painting of {}"],
                   "cat_statue": ["Painting of two {} fishing on a boat",
                                  "A {} backpack",
                                  "Banksy art of {}",
                                  "A {} themed lunchbox",
                                  "Painting of a {} riding a dragon"],
                   "red_teapot": ["A carpet with {} embroidery",
                                  "A {} stamp",
                                  "{} fedora",
                                  "Felt {}"],
                   "clock": ["A photo of {} on the beach",
                             "A photo of {} on the moon",
                             "Elmo holding a {}"],
                   "physics_mug": ["A photo of {} on the beach",
                                   "A photo of {} on the moon",
                                   "Elmo holding a {}"],
                   "elephant": ["Anime painting of a Kawaii {}",
                                "A mossy {}",
                                "{} skeleton in the National Science Museum",
                                "Negative space painting of {}"],
                   "thin_bird": ["Painting of {} in the style of Monet",
                                 "A banana {}",
                                 "Advertisement brochure for {}",
                                 "{} cookies"],
                   "colorful_teapot": ["Manga drawing of a steaming {}",
                                       "A {} watering can",
                                       "{} Death Star",
                                       "A poster for the movie 'The Teapot' starring {}"],
                   'mug_skulls': ["A {} in the Grand Canyon",
                                  "A {} floating in the sea",
                                  "A {} wearing a Superman outfit"],
                   "dog": ["A {} in a swimming pool",
                           "A {} wearing sunglasses",
                           "A {} oil painting, Ghibli inspired"],
                   "tortoise_plushy": ["A watercolor painting of {} plushy on a mountain",
                                       "A {} backpack",
                                       "A {} wearing a Superman outfit"],
                   "teddybear": ["{} in Times Square",
                                 "{} wearing a fedora cap",
                                 "{} wearing a beret cap"],
                   "table": ["{} and an orange sofa",
                             "Photo of a {} and a chair in the garden",
                             "A mossy {}"],
                   "flower": ["A {} with violet color petals",
                              "{} in a wooden pot on a table",
                              "A {} in the Grand Canyon"],
                   "cat": ["{} wearing sunglasses",
                           "A chair with the {} sitting on it near a beach",
                           "{} is sitting inside a wooden pot and looking up"],
                   "chair": ["{} with a cat sitting on it near a beach",
                             "Photo of a table and a {} in the garden",
                             "Ukiyo-e painting of {}"],
                   "wooden_pot": ["A cat is sitting inside a {} and looking up",
                                  "A flower in the {} on a table",
                                  "Elmo holding a {}"],
                   "barn": ["{} made of chocolate",
                            "Photo of a table and a {} in the garden",
                            "A photo of {} on the moon"],
                   "backpack": ["a {} on top of pink fabric",
                           "a {} floating in an ocean of milk",
                           "a {} on the beach",
                           "a {} with a city in the background"],
                   "backpack_dog": ["a {} with a city in the background",
                           "a {} with the Eiffel Tower in the background",
                           "a {} on top of a dirt road",
                           "a cube shaped {}"],
                   "bear_plushie": ["a {} floating in an ocean of milk",
                           "a {} with a mountain in the background",
                           "a {} with a blue house in the background",
                           "a {} on top of a wooden floor"],
                   "berry_bowl": ["a {} floating on top of water",
                           "a wet {}",
                           "a {} with a mountain in the background",
                           "a {} on top of a white rug"],
                   "can": ["a purple {}",
                           "a {} with a blue house in the background",
                           "a cube shaped {}",
                           "a {} on top of a white rug"],
                   "candle": ["a {} on the beach",
                           "a {} floating in an ocean of milk",
                           "a red {}",
                           "a {} with a city in the background"],
                   "cat1": ["a {} on top of a dirt road",
                           "a {} with a blue house in the background",
                           "a {} on top of a mirror",
                           "a {} with the Eiffel Tower in the background"],
                   "cat2": ["a {} in the jungle",
                           "a {} on top of a mirror",
                           "a {} with a city in the background",
                           "a {} on top of a dirt road"],
                   "clock1": ["a {} in the jungle",
                           "a {} on top of the sidewalk in a crowded street",
                           "a {} with a tree and autumn leaves in the background",
                           "a {} on top of green grass with sunflowers around it"],
                   "colorful_sneaker": ["a {} with a blue house in the background",
                           "a purple {}",
                           "a shiny {}",
                           "a {} in the jungle"],
                   "dog1": ["a {} on top of a mirror",
                           "a {} with a blue house in the background",
                           "a {} on the beach",
                           "a {} floating in an ocean of milk"],
                   "dog2": ["a {} on top of the sidewalk in a crowded street",
                           "a {} floating in an ocean of milk",
                           "a {} on top of the sidewalk in a crowded street",
                           "a {} on top of the sidewalk in a crowded street"],
                   "dog3": ["a {} on top of the sidewalk in a crowded street",
                           "a {} on top of a mirror",
                           "a {} with the Eiffel Tower in the background",
                           "a red {}"],
                   "dog5": ["a {} in the jungle",
                           "a {} with the Eiffel Tower in the background",
                           "a {} with a tree and autumn leaves in the background",
                           "a {} on top of the sidewalk in a crowded street"],
                   "dog6": ["a {} with a mountain in the background",
                           "a {} on the beach",
                           "a {} with a blue house in the background",
                           "a {} on top of green grass with sunflowers around it"],
                   "dog7": ["a {} floating in an ocean of milk",
                           "a {} on top of pink fabric",
                           "a {} floating in an ocean of milk",
                           "a {} with a mountain in the background"],
                   "dog8": ["a {} with a city in the background",
                           "a {} with a blue house in the background",
                           "a {} on the beach",
                           "a {} on top of a wooden floor"],
                   "duck_toy": ["a {} on top of a mirror",
                           "a {} on top of a mirror",
                           "a {} on top of a purple rug in a forest",
                           "a {} in the jungle"],
                   "fancy_boot": ["a {} on the beach",
                           "a {} in the jungle",
                           "a {} with a blue house in the background",
                           "a {} with a wheat field in the background"],
                   "grey_sloth_plushie": ["a {} on top of a white rug",
                           "a {} with a tree and autumn leaves in the background",
                           "a {} on top of green grass with sunflowers around it",
                           "a wet {}"],
                   "monster_toy": ["a {} floating on top of water",
                           "a {} in the snow",
                           "a shiny {}",
                           "a {} on a cobblestone street"],
                   "pink_sunglasses": ["a {} floating in an ocean of milk",
                           "a {} with a mountain in the background",
                           "a {} with a tree and autumn leaves in the background",
                           "a {} floating in an ocean of milk"],
                   "poop_emoji": ["a {} on top of a mirror",
                           "a {} on top of pink fabric",
                           "a shiny {}",
                           "a {} on top of a white rug"],
                   "rc_car": ["a {} with the Eiffel Tower in the background",
                           "a cube shaped {}",
                           "a {} on top of green grass with sunflowers around it",
                           "a {} on top of a purple rug in a forest"],
                   "red_cartoon": ["a shiny {}",
                           "a {} in the snow",
                           "a {} with a mountain in the background",
                           "a {} on top of a dirt road"],
                   "robot_toy": ["a cube shaped {}",
                           "a wet {}",
                           "a wet {}",
                           "a red {}"],
                   "shiny_sneaker": ["a {} on top of pink fabric",
                           "a {} on top of a dirt road",
                           "a {} on top of pink fabric",
                           "a {} on a cobblestone street"],
                   "teapot": ["a {} with the Eiffel Tower in the background",
                           "a shiny {}",
                           "a {} on the beach",
                           "a cube shaped {}"],
                   "vase": ["a red {}",
                           "a {} with a tree and autumn leaves in the background",
                           "a {} on a cobblestone street",
                           "a {} on top of a white rug"],
                   "wolf_plushie": ["a shiny {}",
                           "a purple {}",
                           "a {} in the jungle",
                           "a {} on the beach"],
                  }
